### ISSUE TITLE
hexo配置疑问

### ISSUE THREAD

**Issue by Link-kai** [TankNee/hexo-talk#2]
你好博主，我想给我的hexo博客添加说说页面。

请问您说的：“你必须在博客的 _config.yml 中添加对应的配置字段”

这里的_config.yml是指hexo的_config.yml还是博客主题的_config.yml

我尝试在两个yml分别添加你说的配置，结果都出现了报错

因为好像配置项需要上头多个类似：
![Image](https://github.com/user-attachments/assets/69116093-3a05-4af2-b05a-3191235284a7)

**Comment by TankNee** [comment]
是的，readme的yaml应该少了一点东西

```yaml
talk:
  enable: true 	# 是否启用本插件
  type: flomo		# 说说的数据来源，暂时（1.0.0）只有 flomo 一个选项
  title: Talk		# 页面 title
  theme: Paper	# 设置说说主题，暂时（1.0.0）只有 Paper 这一个选项。
  flomo:
    cookie: 		# 必填项，用于获取 flomo 数据。
    tag:				# 展示哪个标签下的数据
    limit: 30		# 展示多少条说说
```

试着加上talk
